## Demo: Build and update Q-tables

In [1]:
import gym
import numpy as np
import random
import matplotlib.pyplot as plt
%matplotlib inline

env = gym.make('FrozenLake-v0')

[2018-02-23 15:14:25,756] Making new env: FrozenLake-v0


In [2]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [3]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[2.25094571e-01 7.84023714e-03 6.40285120e-03 6.00414870e-03]
 [1.03573258e-03 1.12538441e-04 5.02409717e-04 1.76579501e-01]
 [3.63221924e-03 2.16355699e-03 5.75539049e-03 2.79143850e-01]
 [2.03956110e-04 1.34670361e-03 3.27968892e-04 2.20072554e-02]
 [3.86180668e-01 7.83072895e-05 6.97186941e-04 1.74695343e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.74351418e-04 2.02811376e-06 1.18782770e-01 2.90052094e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.37229498e-03 0.00000000e+00 1.19306209e-03 3.38309382e-01]
 [1.84143217e-03 3.99062039e-01 0.00000000e+00 0.00000000e+00]
 [1.08084678e-01 1.19488819e-03 2.41984186e-04 1.03772879e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.91024796e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 6.03141321e-01]
 [0.00000000e+00 0.00000000e+00 0.

In [4]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.4905
